---
  - name: Ensure zsh is installed
    apt: name={{item}} state=present
    with_items:
      - git
      - git-core
      - zsh
  - name: Clone oh-my-zsh repo
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest={{ohmyzsh_user_home}}/.oh-my-zsh
    become: no

  - name: Create conf folder in home directory
    file: path={{ohmyzsh_user_home}}/conf/ state=directory owner={{ohmyzsh_user}}
    become: no
  - name: Create bin folder in home directory
    file: path={{ohmyzsh_user_home}}/bin/ state=directory owner={{ohmyzsh_user}}
    become: no
    
  - name: deploy .zshrc
    template: src=zshrc.in dest={{ohmyzsh_user_home}}/conf/zshrc owner={{ohmyzsh_user}}
    become: no
    
  - name: remove standard zshrc
    file: path={{ohmyzsh_user_home}}/.zshrc state=absent
    become: no
    
  - name: symlink zshrc
    file: path={{ohmyzsh_user_home}}/.zshrc src={{ohmyzsh_user_home}}/conf/zshrc state=link owner={{ohmyzsh_user}}
    become: no
    
  - name: Set zsh as default shell
    user: name={{ohmyzsh_user}} shell=/bin/zsh
    become: yes