---
  - name: Ensure zsh is installed
    apt: name={{item}} state=present
    with_items:
      - git
      - git-core
      - zsh
    when: ansible_distribution == 'Ubuntu'

  - name: Clone oh-my-zsh repo
    git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh
    become: no

  - name: Create conf folder in home directory
    file: path=~/.conf/ state=directory
    become: no

  - name: Create bin folder in home directory
    file: path=~/bin/ state=directory
    become: no
    
  - name: determine if .zshrc already exist
    stat:
      path: ~/.conf/zshrc
    register: zshrc_exists
    become: no

  - name: deploy .zshrc
    template: src=zshrc.in dest=~/.conf/zshrc
    become: no
    when: zshrc_exists.stat.exists == False 
    
  - name: remove standard zshrc
    file: path=~/.zshrc state=absent
    become: no
    
  - name: symlink zshrc
    file: path=~/.zshrc src=~/.conf/zshrc state=link
    become: no
    
  - name: Set zsh as default shell (Ubuntu)
    user: name={{ansible_user_id}} shell=/bin/zsh
    become: yes
    when: ansible_distribution == 'Ubuntu'  
  
  - name: Set zsh as default shell (macOS)
    user: name={{ansible_user_id}} shell=/usr/local/bin/zsh
    become: yes
    when: ansible_distribution == 'MacOSX'